# Generated by Django 3.2.18 on 2023-03-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230307_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
    ]
