# Generated by Django 3.2.18 on 2023-03-12 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
    ]
